// Generated by CoffeeScript 1.3.3
(function() {

  window.Beat = (function() {

    function Beat(_arg) {
      var _this = this;
      this.bpm = _arg.bpm;
      this.bpm || (this.bpm = 60);
      this.bps = this.bpm / 60;
      this.timer = accurateInterval(1000 / this.bps, function() {
        return _this.trigger('beat');
      });
    }

    _.extend(Beat.prototype, Backbone.Events);

    return Beat;

  })();

}).call(this);
