// Generated by CoffeeScript 1.3.3
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  Echotron.Stage = (function() {

    function Stage() {
      this.render = __bind(this.render, this);

      this.animate = __bind(this.animate, this);

      this.update = __bind(this.update, this);
      this.initEngine();
      this.initSong();
    }

    Stage.prototype.initEngine = function() {
      var container;
      this.scene = new THREE.Scene;
      this.scene.fog = new THREE.Fog(0x111111, 0, 5000);
      this.camera = new THREE.PerspectiveCamera(70, window.innerWidth / window.innerHeight, 1, 5000);
      this.camera.position.set(0, 0, -60);
      this.camera.lookAt(new THREE.Vector3(0, 0, 0));
      this.scene.add(this.camera);
      container = document.createElement('div');
      document.body.appendChild(container);
      this.renderer = new THREE.WebGLRenderer({
        antialias: true
      });
      this.renderer.setSize(window.innerWidth, window.innerHeight);
      container.appendChild(this.renderer.domElement);
      this.stats = new Stats;
      $(document.body).append(this.stats.domElement);
      this.layerStack = new Echotron.LayerStack;
      return THREEx.WindowResize(this.renderer, this.camera);
    };

    Stage.prototype.initSong = function() {
      var eventType, _fn, _i, _len, _ref, _ref1,
        _this = this;
      this.song = this.scene.song = new Echotron.Song;
      _ref = ['bar', 'beat', 'tatum', 'segment'];
      _fn = function(eventType) {
        return _this.song.on(eventType, function(eventData) {
          return _this.layerStack[eventType](eventData);
        });
      };
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        eventType = _ref[_i];
        _fn(eventType);
      }
      this.song.on('section', function(section) {
        return _this.layerStack.transition();
      });
      return this.songName = ((_ref1 = window.location.search.match(/^\?(\w+)$/)) != null ? _ref1[1] : void 0) || '90bpm';
    };

    Stage.prototype.start = function(playAudio) {
      var _this = this;
      if (playAudio == null) {
        playAudio = true;
      }
      this.lastFrame = Date.now() / 1000;
      return this.song.load(this.songName, function() {
        _this.song.start(playAudio);
        return _this.animate();
      });
    };

    Stage.prototype.update = function() {
      var elapsed, now;
      now = Date.now() / 1000;
      elapsed = now - this.lastFrame;
      this.lastFrame = now;
      return this.layerStack.update(elapsed);
    };

    Stage.prototype.animate = function() {
      requestAnimationFrame(this.animate);
      this.update();
      this.render();
      this.stats.end();
      return this.stats.begin();
    };

    Stage.prototype.render = function() {
      return this.renderer.render(this.scene, this.camera);
    };

    return Stage;

  })();

  $(function() {
    var stage;
    stage = window.stage = new Echotron.Stage;
    if (typeof mocha === "undefined" || mocha === null) {
      return stage.start(true);
    }
  });

}).call(this);
