// Generated by CoffeeScript 1.3.3
(function() {

  Array.prototype.random || Object.defineProperty(Array.prototype, 'random', {
    value: function() {
      return this[Math.floor(Math.random() * this.length)];
    }
  });

  THREE.Vector3.temp = function(x, y, z) {
    var v, _base;
    v = (_base = THREE.Vector3)._temp || (_base._temp = new THREE.Vector3);
    if ((x != null) && x instanceof THREE.Vector3) {
      v.copy(x);
    } else if ((x != null) && (y != null) && (z != null)) {
      v.set(x, y, z);
    } else if (x != null) {
      v.set(x, x, x);
    }
    return v;
  };

  Number.prototype.rad || Object.defineProperty(Number.prototype, 'rad', {
    get: function() {
      return this * Math.PI / 180;
    }
  });

  Number.prototype.deg || Object.defineProperty(Number.prototype, 'deg', {
    get: function() {
      return this * 180 / Math.PI;
    }
  });

}).call(this);
