// Generated by CoffeeScript 1.3.3
(function() {

  mocha.setup('bdd');

  chai.should();

  $(function() {
    $('body').append($('<div>').attr({
      id: 'mocha'
    }));
    return mocha.run();
  });

}).call(this);
