// Generated by CoffeeScript 1.3.3
(function() {

  describe('Stage', function() {
    describe('getHandlerName', function() {
      return it('translates an event name to a standardized handler name', function() {
        stage.getHandlerName('foo').should === 'onFoo';
        stage.getHandlerName('omgWtf').should === 'onOmgWtf';
        return stage.getHandlerName('segment').should === 'onSegment';
      });
    });
    return it('needs specs');
  });

}).call(this);
