// Generated by CoffeeScript 1.3.3
(function() {

  window.Layers || (window.Layers = {
    _shaders: {}
  });

  Layers.Base = (function() {

    function Base(scene) {
      this.scene = scene;
    }

    Base.prototype.getShader = function(name) {
      var _this = this;
      return Layers._shaders[name] || ($.ajax({
        url: "js/layers/" + name,
        async: false,
        success: function(data) {
          return Layers._shaders[name] = data;
        }
      }), Layers._shaders[name]);
    };

    Base.prototype.getMatProperties = function(name) {
      return {
        vertexShader: this.getShader("" + name + ".vshader"),
        fragmentShader: this.getShader("" + name + ".fshader")
      };
    };

    Base.prototype.beat = function() {};

    Base.prototype.update = function(elapsed) {};

    return Base;

  })();

}).call(this);
