// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.Layers || (window.Layers = {
    _shaders: {}
  });

  Layers.Base = (function(_super) {

    __extends(Base, _super);

    function Base(scene) {
      this.scene = scene;
      Base.__super__.constructor.apply(this, arguments);
      this.scene.add(this);
    }

    Base.prototype.getShader = function(name) {
      var _this = this;
      return Layers._shaders[name] || ($.ajax({
        url: "js/layers/" + name,
        async: false,
        success: function(data) {
          return Layers._shaders[name] = data;
        }
      }), Layers._shaders[name]);
    };

    Base.prototype.getMatProperties = function(name) {
      return {
        vertexShader: this.getShader("" + name + ".vshader"),
        fragmentShader: this.getShader("" + name + ".fshader")
      };
    };

    Base.prototype.beat = function() {};

    Base.prototype.update = function(elapsed) {};

    return Base;

  })(THREE.Object3D);

}).call(this);
