// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Layers.Cubes = (function(_super) {

    __extends(Cubes, _super);

    function Cubes(scene) {
      this.scene = scene;
      Cubes.__super__.constructor.apply(this, arguments);
      this.cubes = [];
    }

    Cubes.prototype.beat = function() {
      var cube;
      cube = new Layers.Cubes.Cube(this);
      this.add(cube);
      return this.cubes.push(cube);
    };

    Cubes.prototype.update = function(elapsed) {
      var cube, tempCubes, _i, _j, _len, _len1, _ref, _ref1;
      _ref = this.cubes;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        cube = _ref[_i];
        cube.update(elapsed);
      }
      tempCubes = [];
      _ref1 = this.cubes;
      for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
        cube = _ref1[_j];
        if (cube.expired) {
          this.remove(cube);
        } else {
          tempCubes.push(cube);
        }
      }
      return this.cubes = tempCubes;
    };

    return Cubes;

  })(Layers.Base);

  Layers.Cubes.Cube = (function(_super) {

    __extends(Cube, _super);

    function Cube() {
      var material, size;
      Cube.__super__.constructor.apply(this, arguments);
      material = {};
      this.uniforms = {
        beatScale: {
          type: 'f',
          value: 1
        }
      };
      size = THREE.Math.randFloat(100, 200);
      this.mesh = new THREE.Mesh(new THREE.CubeGeometry(size, size, size, 1, 1, 1), new THREE.ShaderMaterial(_.extend(this.getMatProperties('cube'), {
        uniforms: this.uniforms
      })));
      this.add(this.mesh);
      this.shrinkTime = THREE.Math.randFloat(2, 6);
      this.rotSpeed = THREE.Math.randFloatSpread(180 * (Math.PI / 180));
      this.mesh.position.set(THREE.Math.randFloatSpread(400), THREE.Math.randFloatSpread(400), THREE.Math.randFloatSpread(400));
    }

    Cube.prototype.beat = function() {
      return this.uniforms.beatScale.value = 1;
    };

    Cube.prototype.update = function(elapsed) {
      this.uniforms.beatScale.value -= elapsed / this.shrinkTime;
      this.mesh.rotation.y += this.rotSpeed * elapsed;
      if (this.uniforms.beatScale.value <= 0) {
        return this.expired = true;
      }
    };

    return Cube;

  })(Layers.Base);

}).call(this);
