// Generated by CoffeeScript 1.3.3
(function() {

  window.Component = (function() {

    function Component() {}

    Component.prototype.update = function(elapsed) {};

    return Component;

  })();

}).call(this);
